#staticdir = "./web/static"
templatedir = "./web/template"
templatedev = true
user = "ubintern"
password = "test"
addr = "localhost:8056"
addrext = "https://search.basel-collections.ch"

[domain]
"edoc.unibas.ch" = "edoc"
"swisscollections.ch" = "swisscollections"
"mediathek.hgk.fhnw.ch" = "Mediathek Basel"

[google]
apikey = "apikey"
    [google.searchkeys.baselcollections]
        key = "baselcollections_key"
        name = "Basel Collections"
        link = "https://www.basel-collections.ch"
    [google.searchkeys.musikwissenschaft]
        key = "musikwissenschaft_key"
        name = "Musikwissenschaft"
        link = "https://ub.unibas.ch/de/fachgebiete/musikwissenschaft/"
    [google.searchkeys.kunstgeschichte]
        key = "kunstgeschichte_key"
        name = "Kunstgeschichte"
        link = "https://ub.unibas.ch/de/kunstgeschichte/"
    [google.searchkeys.openglam]
        key = "openglam_key"
        name = "GLAM Open Access"
        link = ""